
name: 'loadcsv'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'loadcsv'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  database_name: "{{ env_var('TARGET_SNOWFLAKE_DATABASE')}}"
  schema_name: "{{ env_var('TARGET_SNOWFLAKE_SCHEMA')}}"

seeds:
  uh_ifr:
    +schema: seed_data

models:
  loadcsv:
    create_sf_db_and_schema:
      materialized: ephemeral